### ISSUE TITLE
app redirect

### ISSUE THREAD

**Issue by sigkillchris** [jasonjoh/java-tutorial#4]
I'm not if it's me or something changed. I think the redirect path you put in the microsoft app page should be:
`http://localhost:8080/java-tutorial/authorize.html`

If(this is a big if because I'm new to programming). I'm reading this right, your context path is:
`/java-tutorial/`
Meaning things below that should also follow that same convention. Which they do per your request mappings, pages.xml, web.xml, and dispatcher-servlet.xml. 

Please tell me if I missed something as I enjoy learning.

**Comment by jasonjoh** [comment]
It has been a little while since I wrote this, and it's possible that the tools have changed. But at the time of the writing, the `java-tutorial` directory on your machine was the root of the project, so it was not a segment in URLs. (See screenshots in the tutorial at https://docs.microsoft.com/en-us/outlook/rest/java-tutorial).

Have you tried it?
